=== o-ikne/Database-Project-Building-an-XML-database/encooding scheme/rh.dtd
<!ELEMENT rh (employe*)>

<!ELEMENT employe (departement)>
<!ATTLIST employe
          nom CDATA #REQUIRED
          prenom CDATA #REQUIRED
          salaire CDATA #REQUIRED
          taux CDATA #IMPLIED>

<!ELEMENT departement (#PCDATA)>
<!ATTLIST departement
          ville CDATA #REQUIRED>

=== o-ikne/Database-Project-Building-an-XML-database/encooding scheme/rh.xml
<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE rh SYSTEM "rh.dtd">
<rh>
  <employe nom="Patamob" prenom="Adhemar" salaire="50000">
    <departement ville="Paris">Administration</departement>
  </employe>
  <employe nom="Zeublouze" prenom="Agathe" salaire="35000">
    <departement ville="Paris">Distribution</departement>
  </employe>
  <employe nom="Kuzbidon" prenom="Alex" salaire="34000">
    <departement ville="Paris">Vente</departement>
  </employe>
  <employe nom="Locale" prenom="Anasthasie" salaire="36000">
    <departement ville="Paris">Finance</departement>
  </employe>
  <employe nom="Teutmaronne" prenom="Armand" salaire="36000">
    <departement ville="Paris">Administration</departement>
  </employe>
  <employe nom="Zoudanlkou" prenom="Debbie" salaire="25000">
    <departement ville="Paris">Distribution</departement>
  </employe>
  <employe nom="Rivenbusse" prenom="Elsa" salaire="24000">
    <departement ville="Grenoble">Distribution</departement>
  </employe>
  <employe nom="Ardelpic" prenom="Helmut" salaire="23000">
    <departement ville="Lille">Distribution</departement>
  </employe>
  <employe nom="Peursconla" prenom="Humphrey" salaire="22000">
    <departement ville="Marseille">Distribution</departement>
  </employe>
  <employe nom="Vrante" prenom="Helena" salaire="21000">
    <departement ville="Lyon">Distribution</departement>
  </employe>
  <employe nom="Enfaillite" prenom="Melusine" salaire="25000" taux="10">
    <departement ville="Paris">Vente</departement>
  </employe>
  <employe nom="Eurktumeme" prenom="Odile" salaire="26000" taux="12">
    <departement ville="Grenoble">Vente</departement>
  </employe>
  <employe nom="Hotdeugou" prenom="Olaf" salaire="27000" taux="10">
    <departement ville="Lille">Vente</departement>
  </employe>
  <employe nom="Odlavieille" prenom="Pacome" salaire="25500" taux="15">
    <departement ville="Marseille">Vente</departement>
  </employe>
  <employe nom="Amartakaldire" prenom="Quentin" salaire="23000" taux="18">
    <departement ville="Lyon">Vente</departement>
  </employe>
  <employe nom="Traibien" prenom="Samira" salaire="15000">
    <departement ville="Paris">Distribution</departement>
  </employe>
  <employe nom="Fonfec" prenom="Sophie" salaire="14000">
    <departement ville="Paris">Distribution</departement>
  </employe>
  <employe nom="Fairant" prenom="Teddy" salaire="13000">
    <departement ville="Grenoble">Distribution</departement>
  </employe>
  <employe nom="Blaireur" prenom="Terry" salaire="13000">
    <departement ville="Grenoble">Distribution</departement>
  </employe>
  <employe nom="Ajerre" prenom="Tex" salaire="13000">
    <departement ville="Lille">Distribution</departement>
  </employe>
  <employe nom="Chmonfisse" prenom="Thierry" salaire="12000">
    <departement ville="Lille">Distribution</departement>
  </employe>
  <employe nom="Phototetedemort" prenom="Thomas" salaire="22500">
    <departement ville="Marseille">Distribution</departement>
  </employe>
  <employe nom="Kaecoute" prenom="Xavier" salaire="11500">
    <departement ville="Marseille">Vente</departement>
  </employe>
  <employe nom="Adrouille-Toultan" prenom="Yves" salaire="11000">
    <departement ville="Lyon">Distribution</departement>
  </employe>
  <employe nom="Anchier" prenom="Yvon" salaire="10000">
    <departement ville="Lyon">Distribution</departement>
  </employe>
</rh>
